---
abstract: 'Benchmark accessor generators'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  App::Benchmark: 0
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Benchmark-Accessors
provides:
  App::Benchmark::Accessors:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithAccessors:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithClassAccessor:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithClassAccessorClassy:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithClassAccessorComplex:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithClassAccessorConstructor:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithClassAccessorFast:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithClassAccessorFastXS:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithClassAccessorLite:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithClassMethodMaker:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithClassSpiffy:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithClassXSAccessor:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithClassXSAccessorArray:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithClassXSAccessorCompat:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithMojo:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithMoose:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithMooseImmutable:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithMouse:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithMouseImmutable:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithObjectTiny:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithObjectTinyXS:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithRose:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithRubyishAttribute:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
  WithSpiffy:
    file: lib/App/Benchmark/Accessors.pm
    version: 1.110100
requires:
  Class::Accessor: 0
  Class::Accessor::Classy: 0
  Class::Accessor::Complex: 0
  Class::Accessor::Constructor: 0
  Class::Accessor::Fast: 0
  Class::Accessor::Fast::XS: 0
  Class::Accessor::Lite: 0
  Class::MethodMaker: 0
  Class::Spiffy: 0
  Class::XSAccessor: 0
  Class::XSAccessor::Array: 0
  Class::XSAccessor::Compat: 0
  Mojo::Base: 0
  Moose: 0
  Mouse: 0
  Object::Tiny: 0
  Rose::Object: 0
  Rose::Object::MakeMethods::Generic: 0
  Rubyish::Attribute: 0
  Spiffy: 0
  accessors: 0
  parent: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=App-Benchmark-Accessors
  homepage: http://search.cpan.org/dist/App-Benchmark-Accessors/
  repository: git://github.com/hanekomu/App-Benchmark-Accessors.git
version: 1.110100
