---
abstract: 'Benchmark accessor generators'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Benchmark-Accessors
no_index:
  directory:
    - inc
    - t
requires:
  App::Benchmark: 0.02
  Class::Accessor: 0
  Class::Accessor::Classy: 0
  Class::Accessor::Complex: 0
  Class::Accessor::Constructor: 0
  Class::Accessor::Fast: 0
  Class::Accessor::Fast::XS: 0
  Class::MethodMaker: 0
  Class::Spiffy: 0
  Class::XSAccessor: 0
  Class::XSAccessor::Array: 0
  Mojo::Base: 0
  Moose: 0
  Mouse: 0
  Object::Tiny: 0
  Rose::Object: 0
  Rubyish::Attribute: 0
  Spiffy: 0
  UNIVERSAL::require: 0
  accessors: 0
  perl: 5.6.0
resources:
  homepage: http://search.cpan.org/dist/App-Benchmark-Accessors/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/app-benchmark-accessors.git
version: 0.07
